spring:
  datasource:
    url: jdbc:mysql://10.1.56.246:3306/emarket
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.id.new_generator_mappings: false
      hibernate.format_sql: true
  zipkin:
    base-url: http://zipkinservice:9411
          
    
eureka:  
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discoveryservice:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
